const Z={wayanad:{name:'Wayanad, Kerala',lat:11.6854,lon:76.132,terrain:.82},darjeeling:{name:'Darjeeling, West Bengal',lat:27.041,lon:88.2663,terrain:.90},nilgiris:{name:'Nilgiris, Tamil Nadu',lat:11.4102,lon:76.695,terrain:.78},sikkim:{name:'Sikkim',lat:27.533,lon:88.5122,terrain:.92},uttarakhand:{name:'Uttarakhand',lat:30.0668,lon:79.0193,terrain:.88}};
const $=x=>document.querySelector(x);function menu(){let b=$('.menu'),n=document.querySelector('nav');if(b)b.onclick=()=>n.classList.toggle('open')}
async function data(k){let z=Z[k],u=`https://api.open-meteo.com/v1/forecast?latitude=${z.lat}&longitude=${z.lon}&current=temperature_2m,relative_humidity_2m,precipitation&hourly=precipitation,soil_moisture_0_to_1cm&past_hours=24&forecast_hours=1&timezone=auto`,e=`https://api.open-meteo.com/v1/elevation?latitude=${z.lat}&longitude=${z.lon}`;let [a,b]=await Promise.all([fetch(u),fetch(e)]);if(!a.ok||!b.ok)throw Error();let w=await a.json(),el=await b.json(),rain=(w.hourly.precipitation||[]).reduce((x,y)=>x+(+y||0),0),sm=(w.hourly.soil_moisture_0_to_1cm||[]).filter(x=>x!=null);return {z,w,e:el,rain,soil:sm.length?sm.at(-1):null}}
function screen(d){let r=Math.min(d.rain/100,1),s=Math.min((d.soil??.25)/.6,1),t=d.z.terrain,x=.35*r+.25*s+.4*t,label=x>=.78?'CRITICAL':x>=.62?'ELEVATED':x<.35?'NORMAL':'WATCH';return{x,label,r,s,t}}
function map(id){if(!$('#'+id)||typeof L==='undefined')return null;let m=L.map(id).setView([22.5,80.5],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(m);return m}
function color(l){return l==='CRITICAL'?'#ff5d5d':l==='ELEVATED'?'#f2a65a':l==='WATCH'?'#d7c45a':'#72d39b'}
async function markers(m){if(!m)return;let bs=[];for(let k in Z){let z=Z[k],lab='WATCH',score='—';try{let s=screen(await data(k));lab=s.label;score=Math.round(s.x*100)}catch(e){}L.circleMarker([z.lat,z.lon],{radius:9,color:'#06100c',weight:2,fillColor:color(lab),fillOpacity:.9}).addTo(m).bindPopup(`<b>${z.name}</b><br>${lab} monitoring<br><small>Prototype screening: ${score}/100<br>Not an official warning.</small>`);bs.push([z.lat,z.lon])}m.fitBounds(bs,{padding:[25,25]})}
function fill(d,p){let s=screen(d),set=(id,v)=>{let e=$(id);if(e)e.textContent=v};set('#'+p+'Rain',d.rain.toFixed(1));set('#'+p+'Soil',d.soil==null?'—':d.soil.toFixed(3));set('#'+p+'Temp',(+d.w.current.temperature_2m).toFixed(1));set('#'+p+'Elev',Math.round(d.e.elevation[0]));set('#'+p+'Risk',s.label);let bars=[['#barRain',s.r],['#barSoil',s.s],['#barTerrain',s.t]];bars.forEach(([i,v])=>{if($(i))$(i).style.width=v*100+'%'});return s}
async function home(){let m=map('map');markers(m);try{let d=await data('wayanad'),s=fill(d,'home');$('#heroRisk').textContent=s.label;$('#status').textContent='● Environmental feed connected · Wayanad selected'}catch(e){$('#status').textContent='● Environmental feed unavailable'}}
async function monitor(){let s=$('#zone'),m=map('monitorMap'),mk;if(!s)return;async function load(){let z=Z[s.value];if(mk)m.removeLayer(mk);mk=L.marker([z.lat,z.lon]).addTo(m).bindPopup(z.name).openPopup();m.setView([z.lat,z.lon],8);try{fill(await data(s.value),'m');$('#updated').textContent='Updated from live API'}catch(e){$('#updated').textContent='API unavailable'}}s.onchange=load;load()}
async function dash(){let s=$('#dashSelect'),m=map('dashMap'),mk;if(!s)return;async function load(){let z=Z[s.value];$('#dashZone').textContent=z.name;if(mk)m.removeLayer(mk);mk=L.marker([z.lat,z.lon]).addTo(m).bindPopup(z.name).openPopup();m.setView([z.lat,z.lon],7);try{let d=await data(s.value),x=fill(d,'d');$('#dashReason').textContent=`Screening index ${Math.round(x.x*100)}/100 · not a validated ML probability`}catch(e){$('#dashRisk').textContent='OFFLINE'}}s.onchange=load;load()}
document.addEventListener('DOMContentLoaded',()=>{menu();if($('#map'))home();if($('#monitorMap'))monitor();if($('#dashMap'))dash()});
